language: ruby
bundler_args: --without debugging documentation
rvm:
  - 2.6.2
env:
  global:
    - LANG="en_US.UTF-8"
  matrix: 
    # - MAX_THREADS=20 
    # - MAX_THREADS=30
    - MAX_THREADS=50
    # - MAX_THREADS=100
 
script: 
  - bundle exec ruby bench-random.rb
  - while bundle exec ruby bench-update.rb ; do :; done

before_install:
  - gem install bundler -v "~> 1.17"
