language: ruby
bundler_args: --without debugging documentation
rvm:
  - 2.6.2
env:
  - MAX_THREADS=20 LANG="en_US.UTF-8"
  - MAX_THREADS=50 LANG="en_US.UTF-8"
  - MAX_THREADS=100 LANG="en_US.UTF-8"
  - MAX_THREADS=500 LANG="en_US.UTF-8"
 
script: 
  - bundle exec ruby bench-random.rb
  - bundle exec ruby bench-update.rb

before_install:
  - gem install bundler -v "~> 1.17"
